// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1N3mrYZYvpT6gyhhDX70z_TqNzDbLhV0',
    appId: '1:873012973835:web:0ef135d1e02d4be76b920e',
    messagingSenderId: '873012973835',
    projectId: 'deaflypedia-app-d22bf',
    authDomain: 'deaflypedia-app-d22bf.firebaseapp.com',
    storageBucket: 'deaflypedia-app-d22bf.firebasestorage.app',
    measurementId: 'G-7P1VK9V9LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBb94fRrmk2uo75-2zPVIDuE4UeytKAJoE',
    appId: '1:873012973835:android:607c4ad7a8d700f66b920e',
    messagingSenderId: '873012973835',
    projectId: 'deaflypedia-app-d22bf',
    storageBucket: 'deaflypedia-app-d22bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM79NZr7mQMg1vC7-nu7koH6cCeYIwVJU',
    appId: '1:873012973835:ios:fd5cc646dd99661c6b920e',
    messagingSenderId: '873012973835',
    projectId: 'deaflypedia-app-d22bf',
    storageBucket: 'deaflypedia-app-d22bf.firebasestorage.app',
    iosBundleId: 'com.ravenclawcode.deaflypediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM79NZr7mQMg1vC7-nu7koH6cCeYIwVJU',
    appId: '1:873012973835:ios:fd5cc646dd99661c6b920e',
    messagingSenderId: '873012973835',
    projectId: 'deaflypedia-app-d22bf',
    storageBucket: 'deaflypedia-app-d22bf.firebasestorage.app',
    iosBundleId: 'com.ravenclawcode.deaflypediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1N3mrYZYvpT6gyhhDX70z_TqNzDbLhV0',
    appId: '1:873012973835:web:35ff3aaf15b6783c6b920e',
    messagingSenderId: '873012973835',
    projectId: 'deaflypedia-app-d22bf',
    authDomain: 'deaflypedia-app-d22bf.firebaseapp.com',
    storageBucket: 'deaflypedia-app-d22bf.firebasestorage.app',
    measurementId: 'G-FZ9FR4RJZS',
  );
}
