// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPOuWUyK6CES9_F0E_T2_4yY7jBTXC5G4',
    appId: '1:198554205229:web:8ba23f5f710357dc648ca4',
    messagingSenderId: '198554205229',
    projectId: 'daeflypedia-app-firebase',
    authDomain: 'daeflypedia-app-firebase.firebaseapp.com',
    storageBucket: 'daeflypedia-app-firebase.firebasestorage.app',
    measurementId: 'G-2T1BSNWYCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn1HDt0iz6njqFO6QMMe2XXC8YhoS7mKw',
    appId: '1:198554205229:android:1878037fc21edaff648ca4',
    messagingSenderId: '198554205229',
    projectId: 'daeflypedia-app-firebase',
    storageBucket: 'daeflypedia-app-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRhg2NDmLyzh1u-iN_aL_d-cJPQpsyVg',
    appId: '1:198554205229:ios:b9e5f00948288e0f648ca4',
    messagingSenderId: '198554205229',
    projectId: 'daeflypedia-app-firebase',
    storageBucket: 'daeflypedia-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.deaflypediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRhg2NDmLyzh1u-iN_aL_d-cJPQpsyVg',
    appId: '1:198554205229:ios:b9e5f00948288e0f648ca4',
    messagingSenderId: '198554205229',
    projectId: 'daeflypedia-app-firebase',
    storageBucket: 'daeflypedia-app-firebase.firebasestorage.app',
    iosBundleId: 'com.example.deaflypediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPOuWUyK6CES9_F0E_T2_4yY7jBTXC5G4',
    appId: '1:198554205229:web:48d76368ca3f2e73648ca4',
    messagingSenderId: '198554205229',
    projectId: 'daeflypedia-app-firebase',
    authDomain: 'daeflypedia-app-firebase.firebaseapp.com',
    storageBucket: 'daeflypedia-app-firebase.firebasestorage.app',
    measurementId: 'G-0JQM5WGP00',
  );
}
